### ISSUE TITLE
Add a registry check to WINPEAS

### ISSUE THREAD

**Issue by unKn0wnUser453** [carlospolop/privilege-escalation-awesome-scripts-suite#16]
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon

**Comment by carlospolop** [comment]
Hello @unKn0wnUser453,

Thank you very much for the issue. Somehow winpeas bat and exe were looking for *HKLM\\**SYSTEM**\Microsoft\Windows NT\CurrentVersion\Winlogon* instead of *HKLM\\**SOFTWARE**\Microsoft\Windows NT\CurrentVersion\Winlogon*

I have updated both codes but not the Winpeas executables. I will add new checks to Winpeas this week and the next week and then I will update the exes.
