### ISSUE TITLE
[suggestion] Enumerate valid CLSID's

### ISSUE THREAD

**Issue by websecnl** [carlospolop/privilege-escalation-awesome-scripts-suite#29]
Please add this feature.

**Comment by carlospolop** [comment]
Hi @websecnl,

Thanks for the suggestion.
A list like all the CLSID's in the machine could be very annoying if it's not useful.
Could let me know where is it useful so we can think when is interesting to list the CLSIDs? Maybe for exploiting Juicy Potato?

**Comment by websecnl** [comment]
@carlospolop 

It is useful for privileges escalation using the Juicy Potato exploit.
this requires enumeration of service CLSID's.

For more information regarding this see: https://github.com/TsukiCTF/Lovely-Potato

**Comment by carlospolop** [comment]
Hi again @websecnl,

The problem in this case is that there are so many CLSIDs that listing them will make very ugly the output of the tool (making it useless in my perspective).
Also, even if Winpeas just list CLSIDs when SeImpersonatePrivilege is discovered, the user probably won't be able to look formore privilege escalation vectors due to the amount od CLSIDs listed.
Moreover, notice that (I think) JuicyPotato is not working in the latest versions of Windows, at least I read something about it some weeks ago.

Thank you for the suggestion but I'm not going to add this feature due to the problems mentioned before.
Please, feel free to make other suggestions in the future.
