### ISSUE TITLE
Not found .ovpn false positive?

### ISSUE THREAD

**Issue by dmknght** [carlospolop/privilege-escalation-awesome-scripts-suite#36]
I'm testing the LinPEASS on my system and i'm having some `.ovpn` files. The result of script showed ".ovpn Not Found" so i'm wondering if this is something wrong in this script or it looks for specific cases?
My ovpn files are in `$HOME/Downloads` and `$HOME/Desktop`.

**Comment by carlospolop** [comment]
Hi @dmknght,
Thank you very much for letting me know this bug.
Yesterday some changes to improve the speed of linpeas were made and apparently that cause that linpeas was looking for ".ovpn" files instead of "*.ovpn" files. I have fix the bug and upload a new linpeas version.
Please, download it and test that it is now working as expected.
Thank you again.
