### ISSUE TITLE
Timers Filtered

### ISSUE THREAD

**Issue by unKn0wnUser453** [carlospolop/privilege-escalation-awesome-scripts-suite#40]
https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/a8b559e9578b0155f651acca52f8148cd2c95149/linPEAS/linpeas.sh#L934

Why is this filtered to be only user timers? 
Ran into this in a CTF where there were timers on the box. I think --user is not needed and the title should be "System Timers" instead.

**Comment by carlospolop** [comment]
Hi @unKn0wnUser453,

I don't remember why I listed only users timers instead of all, but I have updated linpeas and now all timers are listed in the updated section *Processes, Cron, Services & Timers*
BTW, may you share here or to directly to me the write-up of the CTF were this informtion was relevant? I have never saw that in a CTF.

**Comment by unKn0wnUser453** [comment]
Thanks for the fix! 
Here's a write-up of it. I was surprised when linpeas didn't work but linenum did. 
https://davidhamann.de/2020/02/10/htb-writeup-tartarsauce/

**Comment by unKn0wnUser453** [comment]
Looks like the fix should work. Thanks!
