### ISSUE TITLE
Suggestion and Fix for winPEAS.bat

### ISSUE THREAD

**Issue by hackerinthshell** [carlospolop/privilege-escalation-awesome-scripts-suite#41]
Hi,

To make the output colored, you can use this too:
https://github.com/adoxa/ansicon

Just copy ansicon.exe and ANSI32.dll and execute:
```
ansicon.exe -p
```
For Windows xp and 7 I used version 1.66:
https://github.com/adoxa/ansicon/releases/tag/v1.66

And for Windows 10, version 1.89:
https://github.com/adoxa/ansicon/releases/tag/v1.89

There is problem with winPEAS.bat to identify unquoted service paths. To fix this, I modified the following line:
https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/blob/master/winPEAS/winPEASbat/winPEAS.bat#L362
```
echo %%~s | findstr /r /c:"[a-Z][ ][a-Z]" >nul 2>&1 ...
```
to:
```
echo %%~s ^| findstr /r /c:"[a-Z][ ][a-Z]" >nul 2>&1 ...
```
Thanks for this amazing project.

**Comment by carlospolop** [comment]
Hey @hackerinthshell,

Thank you very much for your suggestion and bug report,I have fixed the bug.
Let me find some time these days to test that application to color the output

**Comment by carlospolop** [comment]
Hi mate,

I think that WinPEAS.bat with colours ill be amazing but I don't have the time (at least now) to create the regex needed to highlight the dangerous things and the good configured things.
Also, regarding the use of your purposed tools, I don't know if the users of Winpeas.bat will want to upload an exe and dll in order to have the colors (maybe this also could be interesting for this: https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011)
But, as I have said I don't have time now, so I will put it on the non-priorities features.
Also, remember that if you want to implement this feature, feel free to send a pull request.
