### ISSUE TITLE
v 2.8.5 malfunction in finding passwords in config PHP files

### ISSUE THREAD

**Issue by dickieku** [carlospolop/privilege-escalation-awesome-scripts-suite#69]
It returned false negative results.
Instead it returned the path of the files that without a match with the expr.
Tried to create a file  /var/www/htm/configurations.php with "password = '1234'"
it failed to detect.

**Comment by carlospolop** [comment]
Hi @dickieku,

Thank you for letting me know this issue.
For some reason there was a `grep -v` instead of just a `grep` that caused the behaviour that you commented.
This should be now fined in version linpeasv2.8.6 (last commit).
Please, check if it's fixed for you now and if not, reopen this issue.

**Comment by dickieku** [comment]
hi @carlospolop 
Thank you for your prompt reply, but I am sorry to tell you 2.8.6 is not working too. I use v2.7.3, it works perfectly. I cannot tell why it works, You may take a look to it.
cheers

**Comment by carlospolop** [comment]
I have checked it this time and in the latest version this should be fixed.
Let me know if it's not, and thank you for reporting the bug!
